project:
  type: website

website:
  title: "Ingeniería de Datos"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: recursos/syllabus.qmd
        text: Syllabus
      - href: lecciones/index.qmd
        text: Lecciones

format:
  html:
    theme: cosmo
    toc: true
    smooth-scroll: true