project:
  type: website

website:
  title: "Ingeniería de Datos"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: recursos/syllabus.qmd
        text: Syllabus

format:
  html:
    theme: cosmo
    toc: true
    smooth-scroll: true