project:
  type: website

lang: es

website:
  title: "Ingeniería de Datos"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: recursos/syllabus.qmd
        text: Syllabus
      - href: lecciones/index.qmd
        text: Lecciones
      - href: notebooks/index.qmd
        text: Notebooks
      - href: actividades/index.qmd
        text: Actividades

format:
  html:
    theme: cosmo
    toc: true
    smooth-scroll: true