---
title: "Lecciones"
---

# Unidad I. Introducción a la ingeniería de datos

- [Introducción a los datos](unidad-01/leccion-01.qmd)
- Formatos de datos
- Organización de los datos
- Ciclo de vida de los datos
- Roles en el ecosistema de datos

# Unidad II. Tecnologías de almacenamiento de datos

- Introducción al almacenamiento de datos
- Bases de datos relacionales
- Almacenes analíticos
- Sistemas de almacenamiento de archivos

# Unidad III. Tecnologías de procesamiento de datos

- Introducción al procesamiento de datos
- Procesamiento por lotes
- Procesamiento en tiempo real
- Arquitecturas para el procesamiento de datos

# Unidad IV. Integración de datos y ETL
- Introducción a la integración de datos
- Procesos ETL
- Transformación de datos
- Herramientas de integración de datos

# Unidad V. Calidad y gobernanza de datos

- Importancia de la calidad y gobernanza de datos
- Calidad de los datos
- Gestión de la calidad de datos
- Gobernanza de datos

# Unidad VI. Seguridad en ingeniería de datos

- Importancia de la seguridad de los datos
- Fundamentos de seguridad
- Riesgos y protección de datos
- Buenas prácticas de seguridad
